/* AUTOMATICALLY GENERATED CODE DO NOT MODIFY */
/*   To generate run: "serverpod generate"    */

// ignore_for_file: implementation_imports
// ignore_for_file: library_private_types_in_public_api
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: public_member_api_docs
// ignore_for_file: type_literal_in_constant_pattern
// ignore_for_file: use_super_parameters

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:serverpod_client/serverpod_client.dart' as _i1;
import 'dart:async' as _i2;
import 'package:laserminipod_client/src/protocol/handle.dart' as _i3;
import 'package:laserminipod_client/src/protocol/spraywall_route.dart' as _i4;
import 'package:serverpod_auth_client/serverpod_auth_client.dart' as _i5;
import 'protocol.dart' as _i6;

/// {@category Endpoint}
class EndpointHandle extends _i1.EndpointRef {
  EndpointHandle(_i1.EndpointCaller caller) : super(caller);

  @override
  String get name => 'handle';

  _i2.Future<List<_i3.Handle>> loadAllHandles() =>
      caller.callServerEndpoint<List<_i3.Handle>>(
        'handle',
        'loadAllHandles',
        {},
      );

  /// returns id of created handle
  _i2.Future<int> addHandle(
    int x,
    int y,
    int radius,
  ) =>
      caller.callServerEndpoint<int>(
        'handle',
        'addHandle',
        {
          'x': x,
          'y': y,
          'radius': radius,
        },
      );

  _i2.Future<void> editHandle(
    int id,
    int x,
    int y,
    int radius,
  ) =>
      caller.callServerEndpoint<void>(
        'handle',
        'editHandle',
        {
          'id': id,
          'x': x,
          'y': y,
          'radius': radius,
        },
      );

  _i2.Future<void> removeHandle(int id) => caller.callServerEndpoint<void>(
        'handle',
        'removeHandle',
        {'id': id},
      );
}

/// {@category Endpoint}
class EndpointRoute extends _i1.EndpointRef {
  EndpointRoute(_i1.EndpointCaller caller) : super(caller);

  @override
  String get name => 'route';

  /// Deletes a route from the `spraywallroute` table based on its ID.
  _i2.Future<void> deleteRoute(int id) => caller.callServerEndpoint<void>(
        'route',
        'deleteRoute',
        {'id': id},
      );

  _i2.Future<bool> saveRoute(_i4.SpraywallRoute route) =>
      caller.callServerEndpoint<bool>(
        'route',
        'saveRoute',
        {'route': route},
      );

  /// Returns a new unique ID for a route.
  /// (Optional: Only needed if IDs are not auto-generated by the database.)
  _i2.Future<int> getNewId() => caller.callServerEndpoint<int>(
        'route',
        'getNewId',
        {},
      );

  _i2.Future<List<_i4.SpraywallRoute>> loadAllRoutes() =>
      caller.callServerEndpoint<List<_i4.SpraywallRoute>>(
        'route',
        'loadAllRoutes',
        {},
      );

  /// Checks if a route with the same handles already exists.
  /// Routes are considered equal if they consist of the same handles.
  _i2.Future<bool> existsRouteAlready(_i4.SpraywallRoute route) =>
      caller.callServerEndpoint<bool>(
        'route',
        'existsRouteAlready',
        {'route': route},
      );

  /// Checks if a given name is already assigned to a route.
  _i2.Future<bool> nameAlreadyAssigned(String name) =>
      caller.callServerEndpoint<bool>(
        'route',
        'nameAlreadyAssigned',
        {'name': name},
      );

  /// Test function to check communication.
  _i2.Future<void> test() => caller.callServerEndpoint<void>(
        'route',
        'test',
        {},
      );
}

/// {@category Endpoint}
class EndpointUser extends _i1.EndpointRef {
  EndpointUser(_i1.EndpointCaller caller) : super(caller);

  @override
  String get name => 'user';

  /// Changes the password for a user.
  _i2.Future<bool> changePassword(
    String email,
    String newPassword,
  ) =>
      caller.callServerEndpoint<bool>(
        'user',
        'changePassword',
        {
          'email': email,
          'newPassword': newPassword,
        },
      );

  /// Checks if the provided password is correct for a user.
  _i2.Future<bool> checkPassword(
    String email,
    String password,
  ) =>
      caller.callServerEndpoint<bool>(
        'user',
        'checkPassword',
        {
          'email': email,
          'password': password,
        },
      );
}

class Modules {
  Modules(Client client) {
    auth = _i5.Caller(client);
  }

  late final _i5.Caller auth;
}

class Client extends _i1.ServerpodClientShared {
  Client(
    String host, {
    dynamic securityContext,
    _i1.AuthenticationKeyManager? authenticationKeyManager,
    Duration? streamingConnectionTimeout,
    Duration? connectionTimeout,
    Function(
      _i1.MethodCallContext,
      Object,
      StackTrace,
    )? onFailedCall,
    Function(_i1.MethodCallContext)? onSucceededCall,
    bool? disconnectStreamsOnLostInternetConnection,
  }) : super(
          host,
          _i6.Protocol(),
          securityContext: securityContext,
          authenticationKeyManager: authenticationKeyManager,
          streamingConnectionTimeout: streamingConnectionTimeout,
          connectionTimeout: connectionTimeout,
          onFailedCall: onFailedCall,
          onSucceededCall: onSucceededCall,
          disconnectStreamsOnLostInternetConnection:
              disconnectStreamsOnLostInternetConnection,
        ) {
    handle = EndpointHandle(this);
    route = EndpointRoute(this);
    user = EndpointUser(this);
    modules = Modules(this);
  }

  late final EndpointHandle handle;

  late final EndpointRoute route;

  late final EndpointUser user;

  late final Modules modules;

  @override
  Map<String, _i1.EndpointRef> get endpointRefLookup => {
        'handle': handle,
        'route': route,
        'user': user,
      };

  @override
  Map<String, _i1.ModuleEndpointCaller> get moduleLookup =>
      {'auth': modules.auth};
}
